import type { Models } from "react-native-appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum PropertiesType {
  HOUSE = "House",
  TOWNHOUSE = "Townhouse",
  CONDO = "Condo",
  DUPLEX = "Duplex",
  STUDIO = "Studio",
  VILLA = "Villa",
  APARTMENT = "Apartment",
  OTHER = "Other",
}

export enum PropertiesFacilities {
  LAUNDRY = "Laundry",
  PARKING = "Parking",
  GYM = "Gym",
  WIFI = "Wifi",
  PET_FRIENDLY = "Pet-Friendly",
}

export type Agents = Models.Row & {
  name: string;
  email: string;
  avatar: string;
};

export type Galleries = Models.Row & {
  image: string;
};

export type Reviews = Models.Row & {
  name: string;
  avatar: string;
  review: string;
  rating: number;
  property: Properties;
};

export type Properties = Models.Row & {
  name: string;
  type: PropertiesType;
  description: string;
  address: string;
  price: number;
  area: number;
  bedrooms: number;
  bathrooms: number;
  rating: number;
  facilities: PropertiesFacilities[] | null;
  image: string;
  geolocation: string;
  agent: Agents;
  gallery: Galleries[];
  reviews: Reviews[];
};
